import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
        {children}
        <script src="http://localhost:3000/embeds/toast.js"
        site-api-key="site_9a60c59f-c247-4af4-8048-855be6898e2a"
        widget-api-key="widget_adf074c9-b2de-4e18-bab0-a1d82f6cce1c"
        ></script>
        </AuthProvider>
      </body>
    </html>
  );
}
